version: "3"

tasks:
  migrateloc:
    aliases:
      - migloc
    desc: "apply migrations to local database"
    cmds:
      - go run cmd/migrator/main.go --storage-path .data/data.db --migrations-path migrations --migrations-table migrations
    aliases:
      - migtest
    desc: "apply migrations to local database from tests"
    cmds:
      - go run cmd/migrator/main.go --storage-path .data/data.db --migrations-path tests/migrations --migrations-table migrations_tests


